# docker build -t pfinal/ubuntu:18.04 . && docker push pfinal/ubuntu:18.04

FROM ubuntu:18.04

LABEL Author="ZouYiliang"

RUN apt-get update \
&& apt-get install -y curl vim-tiny unzip net-tools iputils-ping
