version: '3.4'
services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'abc123'  # root用户的密码

      MYSQL_DATABASE: demo

      MYSQL_USER: demo
      MYSQL_PASSWORD: 'def456'

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1

  php:
    image: 172.19.80.62:5000/myphp:1.0    # 按实际情况修改私有仓库地址
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 3

  nginx:
    image: 172.19.80.62:5000/mynginx:1.0  # 按实际情况修改私有仓库地址
    ports:
      - 8081:80

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 2

  adminer:
    image: adminer
    ports:
        - 8080:8080
