# docker build -t pfinal/ubuntu:16.04 . && docker push pfinal/ubuntu:16.04

FROM ubuntu:16.04

LABEL Author="ZouYiliang"

RUN apt-get update \
&& apt-get install -y curl vim-tiny unzip net-tools iputils-ping
