version: '3.4'
services:

  php:
    image: pfinal/php:7.2-fpm-alpine
    #ports:
    #  - 9000:9000
    volumes:
      - $PWD/code:/www/code/

  nginx:
    image: nginx:alpine
    volumes:
      - $PWD/code/:/www/code/
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    #links:
    #  - php
