version: '3.4'
services:

  php:
    build: .
    ports:
      - 9000:9000
    volumes:
      - /Users/joe/docker/php-project/code/:/www/code/

  nginx:
    image: nginx:alpine
    volumes:
      - /Users/joe/docker/php-project/code/:/www/code/
      - /Users/joe/docker/php-project/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - php
